import type { Question } from "./types";

const ABSTRAKT_OPTIONS = [
  "celé vety, slovesá v trpnom rode, v tretej osobe a využíva sa autorský plurál",
  "celé vety, slovesá v činnom rode, v tretej osobe a využíva sa autorský plurál",
  "celé vety, slovesá v trpnom rode, v prvej osobe a využíva sa autorský plurál",
];

const PLAGIAT_OPTIONS = [
  "kúpa",
  "CTRL-C (žalúzie)",
  "hybrid",
  "autoplagizovanie",
  "klonovanie (roleta)",
  "maskovanie",
  "agregátor",
  "recyklovanie",
  "remix",
];

const SOURCE_NOT_RELEVANT_OPTIONS = [
  "vedeckú štúdiu dostupnú na Google Scholar",
  "vedeckú prácu staršiu ako 30 rokov",
  "odborný časopis",
  "vysokoškolské skriptá",
  "stredoškolskú učebnicu",
];

const TEXT_STYLE_OPTIONS = [
  "v prvej osobe množného čísla",
  "nikdy nie v trpnom rode",
  "v prvej osobe jednotného čísla",
  "výlučne v trpnom rode",
];

const CITE_NEMUSIME_OPTIONS = [
  "parafrázovanú myšlienku",
  "všeobecné znalosti, ktoré sú overiteľné v encyklopédiách",
  "grafy a tabuľky na internete",
  "nové termíny",
];

const OBERT_OPTIONS = [
  "(Obert 2006)",
  "(OBERT, 2006)",
  "(Obert, 2006)",
  "(In: Obert, 2006)",
  "(Obert, V., 2006)",
];

const CITACIA_CASOPIS_OPTIONS = [
  "ANDREJČÍKOVÁ, N. Komunikácia a kooperácia IS pre knižnice. Bratislava: CVTI SR, 1999.",
  "ANDREJČÍKOVÁ, N. (1999) Komunikácia a kooperácia. Bulletin Centra. p. 54-59.",
  "ANDREJČÍKOVÁ, N., 1999. Komunikácia a kooperácia IS pre knižnice: úvod do komunikačného protokolu. In: Bulletin Centra vedecko-technických informácií SR. Roč. 3, č. 2, s. 54-59. ISSN 1335-793X.",
];

export const questions: Question[] = [
  {
    id: 1,
    type: "truefalse",
    text: "Na internete sa nenachádzajú vhodné odborné zdroje použiteľné pri spracovaní bakalárskej práce.",
    answer: false,
  },
  {
    id: 2,
    type: "single",
    text: "Pri štylizácii abstraktu sa používajú:",
    options: ABSTRAKT_OPTIONS,
    answer: 0,
  },
  {
    id: 3,
    type: "matching",
    text: "Priraďte časti bakalárskej práce k ich charakteristike:",
    left: ["Úvod", "Záver", "Abstrakt", "Jadro práce"],
    right: [
      "charakterizuje stručne a výstižne význam, dôvody zvolenia témy, jej aktuálnosť a stav poznania danej témy",
      "prináša komplexný pohľad na tému práce a navrhuje riešenia vyplývajúce z porovnania doterajšieho stavu riešeného problému a vlastných záverov",
      "píše sa ako jeden celok",
      "definuje základné (východiskové) pojmy",
    ],
    pairs: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
    ],
  },
  {
    id: 4,
    type: "multi",
    text: "Vyberte jednu alebo viacej možností, ktoré charakterizujú teoretickú časť bakalárskej práce:",
    options: [
      "má analytický charakter, je výsledkom teoretického výskumu v rámci štúdia dostupných literárnych prameňov, ponúka prehľad výskumných zistení v danej oblasti minimálne v slovenskom kontexte",
      "je spracovaná na základe analýzy, syntézy, porovnávania a zovšeobecňovania informácií z literárnych zdrojov",
      "obsahuje informácie o cieľoch práce, jej stručnom obsahu a v závere sa charakterizuje splnenie cieľa, použité metódy, výsledky a závery celej práce",
      "prináša tvorivý vklad autora do riešenej problematiky, pričom sa dotýka vymedzenej oblasti edukačnej reality",
      "obsahuje vecné závery, sumarizáciu práce, vlastný prínos autora, pohľad autora na stanovené ciele a teoretickú platformu",
      "spracúva zvolenú tému na báze reprezentatívneho výberu odbornej literatúry",
    ],
    answers: [0, 1, 5],
  },
  {
    id: 5,
    type: "single",
    text: "Označte bibliografický odkaz na článok v časopise:",
    options: [
      "JANOVSKÁ, Darina, 2018. Digitálna knižnica Gallica. In: Knižnica. Roč. 19, č. 4, s. 16-23. ISSN 1336-0965.",
      "VALACH, Július, 1987. Staré tlačiarne a tlačiari na Slovensku. Martin: Matica slovenská.",
      "STEINEROVÁ, Jela, 2000. Základy filozofie človeka v knižničnej a informačnej vede. In: Š. KIMLIČKA et al., ed. Knižničná a informačná veda na prahu informačnej spoločnosti. Bratislava: Stimul, s. 9-56. ISBN 80-88982-29-4.",
    ],
    answer: 0,
  },
  {
    id: 6,
    type: "truefalse",
    text: "Pri práci so zdrojovou literatúrou by mal študent preukázať porozumenie problematiky tým, že dokáže porovnávať teoretické koncepty a empirické zistenia z viacerých študovaných zdrojov.",
    answer: true,
  },
  {
    id: 7,
    type: "multi",
    text: "Ktoré z uvedených vyjadrení platia pre abstrakt:",
    options: [
      "je povinnou súčasťou bakalárskej práce a umiestňuje sa za titulný list na samostatnú novú stranu",
      "pri štylizácii sa používajú celé vety, slovesá v trpnom rode a v tretej osobe, využíva sa autorský plurál",
      "je vstupnou časťou bakalárskej práce, v ktorej by malo byť uvedené, na čo je práca zameraná, čo bolo podnetom na voľbu danej problematiky",
      "stručne a výstižne charakterizuje stav poznania alebo praxe v oblasti, ktorá je predmetom práce, štruktúru a opis jednotlivých kapitol",
      "píše sa súvisle ako jeden odsek",
      "uvádza sa povinne v slovenskom a anglickom jazyku, každá jazyková verzia sa nachádza na samostatnej strane",
    ],
    answers: [0, 1, 4, 5],
  },
  {
    id: 8,
    type: "single",
    text: "Technika snowballing (technika snehovej gule) je v oblasti práce s informačnými zdrojmi chápaná ako:",
    options: [
      "vyhľadávanie v citačných databázach pomocou kľúčových slov",
      "vyhľadávanie pomocou Boolean operátorov",
      "opakovaná rešerš s postupným rozširovaním zoznamu kľúčových slov",
      "vyhľadávanie referencií v zozname literatúry iných referencií alebo v zozname ich citácií",
    ],
    answer: 3,
  },
  {
    id: 9,
    type: "multi",
    text: "Predstavte si prácu s názvom „Úloha rodiny v sociálnom vývine dieťaťa predškolského veku\". Ktoré 2 z nasledujúcich kapitol by ste vnímali z hľadiska zamerania práce ako problematické, odťažité?",
    options: [
      "Motorický vývin dieťaťa predškolského veku",
      "Vzťah medzi chudobou a výchovným štýlom",
      "Klíma rodinného prostredia",
      "Kompetencie učiteľa predškolského vzdelávania",
    ],
    answers: [0, 3],
    exactCount: 2,
  },
  {
    id: 10,
    type: "single",
    text: "Tabuľky, grafy a obrázky sa číslujú:",
    options: [
      "rímskymi číslicami",
      "arabskými číslicami",
      "tabuľky rímskymi číslicami a grafy, obrázky arabskými číslicami",
    ],
    answer: 1,
  },
  {
    id: 11,
    type: "multi",
    text: "Pri písaní bakalárskej práce za relevantný zdroj nemožno považovať:",
    options: SOURCE_NOT_RELEVANT_OPTIONS,
    answers: [1, 3, 4],
  },
  {
    id: 12,
    type: "single",
    text: "Ktorý citačný zápis sa v univerzitnej smernici používa pre citovanie článku z časopisu?",
    options: CITACIA_CASOPIS_OPTIONS,
    answer: 2,
  },
  {
    id: 13,
    type: "single",
    text: "Kazuistika je:",
    options: [
      "prehľadová štúdia",
      "prípadová štúdia",
      "longitudinálna štúdia",
      "analyticko-interpretačná štúdia",
    ],
    answer: 1,
  },
  {
    id: 14,
    type: "multi",
    text: "Vyberte jednu alebo viac možností, ktoré sú charakteristické pre úvod bakalárskej práce:",
    options: [
      "rozpracúva a analyzuje danú problematiku nielen zo súčasného, ale i historického kontextu",
      "autor tu stručne a výstižne charakterizuje stav poznania alebo praxe v oblasti, ktorá je predmetom práce, štruktúru a opis jednotlivých kapitol, uvádza použité metódy, ich opodstatnenie a uplatnenie v práci",
      "autor tu uvádza dostupné informácie a poznatky z aktuálne publikovaných prác týkajúcich sa danej témy",
      "je vstupnou časťou bakalárskej práce, v ktorej by malo byť uvedené, na čo je práca zameraná, čo bolo podnetom na voľbu danej problematiky, čím je zvolená téma významná, zdôvodnenie aktuálnosti témy práce",
      "krátka, presná, konkrétna a výstižná charakteristika obsahu bakalárskej práce — má umožniť čitateľovi presne a rýchlo identifikovať základný obsah bakalárskej práce",
    ],
    answers: [1, 3],
  },
  {
    id: 15,
    type: "multi",
    text: "K typickým nedostatkom pri výbere informačných zdrojov patrí:",
    options: [
      "čerpanie zo zdrojov starších ako 30 rokov",
      "nesystematický výber informačných zdrojov, náhodný výber (použije sa, čo je po ruke)",
      "nezdôvodnené spoľahnutie sa na nespoľahlivé informačné zdroje",
    ],
    answers: [0, 1, 2],
  },
  {
    id: 16,
    type: "single",
    text: "Ako sa označuje kopírovanie cudzích textov, ktoré sú síce odcitované ale bez vlastného textu?",
    options: PLAGIAT_OPTIONS,
    answer: 6,
  },
  {
    id: 17,
    type: "matching",
    text: "Boolean operátory slúžia na definovanie logiky vzťahov medzi vyhľadávanými výrazmi. Priraďte operátory k ich funkcii:",
    left: [
      "xx filetype:pdf",
      "„xx*yy\"",
      "„xx yy\"",
      "xx OR yy",
      "xx -yy",
    ],
    right: [
      "hľadá iba pdf súbory obsahujúce frázu xx",
      "hľadá akúkoľvek formu výrazu „xx niečoniečoyy\"",
      "hľadá presnú frázu „xx yy\"",
      "stránky obsahujúce xx alebo yy",
      "stránky obsahujúce „xx\" no nie „yy\"",
    ],
    pairs: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
      [4, 4],
    ],
  },
  {
    id: 18,
    type: "single",
    text: "Medzi nepovinné súčasti bakalárskej práce patria:",
    options: [
      "poďakovanie, abstrakt v cudzom jazyku, predhovor, zoznam ilustrácií a zoznam tabuliek",
      "poďakovanie, predhovor, zoznam ilustrácií a zoznam tabuliek, zoznam skratiek a značiek, prílohy",
      "čestné vyhlásenie, poďakovanie, predhovor, zoznam ilustrácií, zoznam tabuliek",
    ],
    answer: 1,
  },
  {
    id: 19,
    type: "single",
    text: "Autor záverečnej práce sa nedopúšťa plagiátorstva, keď do svojho textu zaradí:",
    options: [
      "prevzatú schému, tabuľku alebo obrázok bez uvedenia zdroja",
      "doslovne prevzatý text iného autora, neoznačí ho úvodzovkami, ale uvedie jeho zdroj",
      "krátku formuláciu cudzej myšlienky (teóriu, výrok) bez uvedenia pôvodu (autora)",
      "parafrázované (preformulované) myšlienky iného autora a uvedie ich zdroj a pôvod",
    ],
    answer: 3,
  },
  {
    id: 20,
    type: "single",
    text: "OBERT, V., 2006. Návraty a odkazy. Nitra: Univerzita Konštantína Filozofa. ISBN 80-8094-046-0. Túto monografiu citujeme odkazom v texte ako:",
    options: OBERT_OPTIONS,
    answer: 0,
  },
  {
    id: 21,
    type: "single",
    text: "Ako sa tiež pomenúva kompletné prebratie cudzieho textu bez zmeny a označenia tohto prebratého textu?",
    options: PLAGIAT_OPTIONS,
    answer: 4,
  },
  {
    id: 22,
    type: "single",
    text: "Doslovne prevzatý text zo zdrojového dokumentu, vymedzený úvodzovkami, sa nazýva:",
    options: ["bibliografický odkaz", "zdroj", "citát", "parafráza"],
    answer: 2,
  },
  {
    id: 23,
    type: "truefalse",
    text: "Etika citovania určuje spôsob dodržiavania etickej normy vo vzťahu k cudzím myšlienkam a výsledkom iných informačných zdrojov, ktoré autor v práci využil. Technika citovania vyjadruje, či a ako správne autor spája miesta v texte so záznamami o dokumentoch, ktoré sú v zozname bibliografických odkazov.",
    answer: true,
  },
  {
    id: 24,
    type: "matching",
    text: "Priraďte správnu odpoveď k typu textu / spôsobu práce so zdrojmi:",
    left: [
      "Tvorivý kompilát",
      "Sekundárny kompilát",
      "Presýtenosť citáciami",
      "Kompilát",
      "Skreslené citovanie",
    ],
    right: [
      "Autor sa v tomto texte korektne odvoláva na použité zdroje a dospieva k vlastným záverom a stanoviskám",
      "Preberanie myšlienok z druhotných zdrojov bez overenia v originálnych prameňoch",
      "Nadmerné používanie citátov, pri ktorom v texte chýba dostatočný autorský vklad",
      "Text, ktorý vznikol zostavením myšlienok z iných diel, pričom sa autor v práci jasne a korektne odvoláva na použité zdroje",
      "Nekorektné a obsahovo nepresné preberanie textov, výsledkom čoho je skreslenie pôvodného významu",
    ],
    pairs: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
      [4, 4],
    ],
    note: "⚠️ Definície „Sekundárny kompilát\" a „Presýtenosť citáciami\" boli doplnené z bežnej teórie publikačnej etiky — pri zázname overiť so smernicou.",
  },
  {
    id: 25,
    type: "single",
    text: "Ak chceme v texte výnimočne niečo zvýrazniť, tak použijeme:",
    options: ["podčiarknutie", "bold (tučné)", "kurzívu", "VEĽKÉ PÍSMENÁ"],
    answer: 2,
  },
  {
    id: 26,
    type: "truefalse",
    text: "Nedodržaním etických štandardov v záverečnej práci autor ohrozuje aj samého seba — riskuje disciplinárne konanie pred etickou komisiou fakulty, ktorej závery môžu byť rôzne (nepripustenie ku štátnym skúškam, neobhájenie záverečnej práce, povinnosť ju celú prepracovať či vylúčenie zo štúdia).",
    answer: true,
  },
  {
    id: 27,
    type: "matching",
    text: "Podľa bibliografického zápisu určte, o aký typ zdrojového dokumentu ide:",
    left: [
      "MACEK, P., 2008. Sebesystém, vztah k vlastnímu Já. In: J. Výrost, I. Slameník (Eds.), Sociální psychologie (s. 89 – 107). 2. přepracované a rozšířené vydání. Praha: Grada.",
      "MATZOVÁ, Z., SUROVCOVÁ, A., TREBATICKÁ, J., 2017. Závislosť od internetu u detí a adolescentov. Pediatria pre prax. Roč. 18, č. 5, s. 191 – 193. Dostupné z: http://www.pediatriapreprax.sk/...",
      "BRINDZA, J., 2000. Voľný čas detí a jeho miesto pri formovaní ich životného spôsobu. Rodina a škola. Roč. 48, č. 8, s. 12.",
      "Pravidlá slovenského pravopisu. 3., upravené a doplnené vyd. Bratislava: Veda, 2000.",
      "MISTRÍK, J., 1997. Štylistika. Bratislava: Slovenské pedagogické nakladateľstvo.",
    ],
    right: [
      "kapitola v monografii",
      "elektronický odborný časopis",
      "printový odborný časopis",
      "slovník",
      "monografia, vysokoškolská učebnica",
    ],
    pairs: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
      [4, 4],
    ],
  },
  {
    id: 28,
    type: "single",
    text: "Autorský vklad znamená, že:",
    options: [
      "autor ponúka vlastnú interpretáciu či závery založené na odborných faktoch",
      "autor sprostredkováva názory iných odborníkov na tému",
      "autor ponúka vlastné názory na danú tému",
      "autor sprostredkováva vlastné interpretácie založené na pocitoch vzťahujúcich sa k danej téme",
    ],
    answer: 0,
  },
  {
    id: 29,
    type: "fillin",
    text: "Vytváranie výpiskov z odbornej literatúry pre študijné ciele sa nazýva?",
    accepted: ["excerpcia", "excerpácia"],
    hint: "jedno slovo",
  },
  {
    id: 30,
    type: "multi",
    text: "Pri tvorbe bakalárskej práce sa očakáva, že si študent osvojí (vyberte všetko, čo platí):",
    options: [
      "preveriť a prehĺbiť rozsah a kvalitu vedomostí, návykov a zručností osvojených v priebehu štúdia",
      "prispieť k zvládnutiu vedeckej a odbornej terminológie",
      "rozvíjať pripravenosť na samostatnú a tvorivú činnosť v príslušnom odbore",
      "prispieť k hlbšiemu poznaniu svojich schopností exaktného myslenia a možností sebarealizácie",
      "vytvoriť autorské dielo na komerčné vydanie",
    ],
    answers: [0, 1, 2, 3],
  },
  {
    id: 31,
    type: "fillin",
    text: "Ako sa tiež pomenúva kompletné prebratie cudzieho textu bez zmeny a označenie tohto prebratého textu za vlastný?",
    accepted: ["klonovanie", "roleta", "klonovanie (roleta)"],
  },
  {
    id: 32,
    type: "fillin",
    text: "Ako sa tiež označuje zmena kľúčových slov a fráz v kopírovanom texte, ale zachovanie základného obsahu zdroja?",
    accepted: ["maskovanie"],
  },
  {
    id: 33,
    type: "fillin",
    text: "Ako sa označuje vážne porušenie etiky citovania, ak autor záverečnej práce kombinuje citované a necitované pasáže z cudzích zdrojov?",
    accepted: ["hybrid"],
  },
  {
    id: 34,
    type: "fillin",
    text: "Ako sa nazýva kopírovanie cudzích textov, ktoré sú síce odcitované, ale bez vlastného textu?",
    accepted: ["agregator", "agregátor"],
  },
  {
    id: 35,
    type: "single",
    text: "Ktorý citačný zápis sa v univerzitnej smernici používa pre citovanie článku z časopisu? (opakovanie)",
    options: CITACIA_CASOPIS_OPTIONS,
    answer: 2,
  },
  {
    id: 36,
    type: "single",
    text: "OBERT, V., 2006. Návraty a odkazy. Nitra: Univerzita Konštantína Filozofa. ISBN 80-8094-046-0. Túto monografiu citujeme odkazom v texte ako: (opakovanie)",
    options: OBERT_OPTIONS,
    answer: 0,
  },
  {
    id: 37,
    type: "fillin",
    text: "Najväčším svetovým vyhľadávačom vedeckej literatúry je _________ .",
    accepted: ["google scholar", "scholar google", "scholar"],
  },
  {
    id: 38,
    type: "single",
    text: "Medzi nepovinné súčasti bakalárskej práce patria: (opakovanie)",
    options: [
      "poďakovanie, abstrakt v cudzom jazyku, predhovor, zoznam ilustrácií a zoznam tabuliek",
      "poďakovanie, predhovor, zoznam ilustrácií a zoznam tabuliek, zoznam skratiek a značiek, prílohy",
      "čestné vyhlásenie, poďakovanie, predhovor, zoznam ilustrácií, zoznam tabuliek",
    ],
    answer: 1,
  },
  {
    id: 39,
    type: "single",
    text: "Pri štylizácii abstraktu sa používa: (opakovanie)",
    options: ABSTRAKT_OPTIONS,
    answer: 0,
  },
  {
    id: 40,
    type: "fillin",
    text: "Krátka a výstižná charakteristika obsahu dokumentu, ktorá slúži na jeho presnú a rýchlu identifikáciu, sa nazýva:",
    accepted: ["abstrakt"],
  },
  {
    id: 41,
    type: "single",
    text: "V prípade napr. dvoch autorov uvádzame citačný odkaz v texte vo forme:",
    options: [
      "(Smith a Jones, 2008)",
      "(Smith & Jones, 2008)",
      "(Smith / Jones, 2008)",
      "(Smith, Jones; 2008)",
    ],
    answer: 0,
  },
  {
    id: 42,
    type: "single",
    text: "Tabuľky, grafy a obrázky sa číslujú: (opakovanie)",
    options: [
      "rímskymi číslicami",
      "arabskými číslicami",
      "tabuľky rímskymi číslicami a grafy, obrázky arabskými číslicami",
    ],
    answer: 1,
  },
  {
    id: 43,
    type: "single",
    text: "Rozsah bakalárskej práce bez príloh by mal byť?",
    options: [
      "20-25 normostrán",
      "25-35 normostrán",
      "30-40 normostrán",
      "50-60 normostrán",
    ],
    answer: 2,
  },
  {
    id: 44,
    type: "single",
    text: "Text bakalárskej práce sa podľa smernice má písať:",
    options: TEXT_STYLE_OPTIONS,
    answer: 3,
  },
  {
    id: 45,
    type: "single",
    text: "V odbornom texte nový odsek začíname:",
    options: [
      "keď má odsek viac ako 5 riadkov",
      "keď autor začína novú myšlienku",
      "na konci každej strany",
      "po každej citácii",
    ],
    answer: 0,
    note: "⚠️ V inej verzii podkladov sa ako správna označuje aj odpoveď „novou myšlienkou\" — overiť so zdrojom.",
  },
  {
    id: 46,
    type: "single",
    text: "Počet kľúčových slov práce uvedených v abstrakte by mal byť:",
    options: ["1-2", "2-3", "3-5", "5-10"],
    answer: 2,
  },
  {
    id: 47,
    type: "single",
    text: "Formálne požiadavky odporúčané pre bakalársku prácu zahŕňajú:",
    options: [
      "typ písma Arial, veľkosť 11, riadkovanie 1, číslovanie strán rímskymi číslicami",
      "typ písma Times New Roman, veľkosť 12 s výnimkou nadpisov, riadkovanie 1,5 a priebežné číslovanie strán arabskými číslicami",
      "typ písma Times New Roman, veľkosť 14, riadkovanie 2, bez číslovania strán",
      "typ písma Calibri, veľkosť 11, riadkovanie 1,15, číslovanie strán arabskými číslicami",
    ],
    answer: 1,
  },
  {
    id: 48,
    type: "single",
    text: "Vytváranie výpiskov odbornej alebo umeleckej literatúry pre študijné ciele sa nazýva:",
    options: ["excerpcia", "rešerš", "kompilácia", "jazyková korektúra"],
    answer: 0,
  },
  {
    id: 49,
    type: "single",
    text: "Rozsah bibliografických odkazov:",
    options: [
      "je daný množstvom použitých informačných zdrojov",
      "je limitovaný rozsahom bakalárskej práce",
      "by mal byť v rozsahu aspoň dvoch strán",
    ],
    answer: 0,
  },
  {
    id: 50,
    type: "single",
    text: "Výskumná metóda založená na sledovaní činnosti ľudí, jej zaznamenávaní, analýze a vyhodnotení sa nazýva:",
    options: ["experiment", "pozorovanie", "dotazník", "rozhovor"],
    answer: 1,
  },
  {
    id: 51,
    type: "single",
    text: "Technika citovania vyjadruje:",
    options: [
      "či a ako správne podľa normy autor spája miesta v texte so záznamami o dokumentoch zo zoznamu bibliografických odkazov",
      "ako autor dokáže aplikovať zvolenú techniku citovania v praxi",
      "či a ako správne, podľa normy, autor vytvára zoznam bibliografických odkazov",
    ],
    answer: 0,
  },
  {
    id: 52,
    type: "single",
    text: "Ak opakovane citujeme jedno dielo jedného autora na tej istej strane v bezprostrednej nadväznosti, v texte namiesto bibliografického odkazu môžeme uviesť:",
    options: ["(eds.)", "(tamže)", "(ibid.)", "(s.p.)"],
    answer: 1,
  },
  {
    id: 53,
    type: "multi",
    text: "Pri písaní bakalárskej práce za relevantný zdroj nemožno považovať: (opakovanie)",
    options: [
      "vysokoškolské skriptá",
      "stredoškolskú učebnicu",
      "odborný časopis",
      "vedeckú prácu staršiu ako 30 rokov",
      "vedeckú štúdiu dostupnú na Google Scholar",
    ],
    answers: [0, 1, 3],
  },
  {
    id: 54,
    type: "multi",
    text: "Citovať nemusíme:",
    options: CITE_NEMUSIME_OPTIONS,
    answers: [1],
  },
  {
    id: 55,
    type: "single",
    text: "Text bakalárskej práce sa podľa smernice má písať: (opakovanie)",
    options: TEXT_STYLE_OPTIONS,
    answer: 3,
    note: "Smernica pripúšťa aj 1. osobu množného čísla (autorský plurál) a/alebo trpný rod — overiť presnú formuláciu.",
  },
  {
    id: 56,
    type: "fillin",
    text: "Ak chceme v texte výnimočne niečo zvýrazniť, tak použijeme:",
    accepted: ["kurziva", "kurzívu", "kurzíva", "italika"],
  },
  {
    id: 57,
    type: "fillin",
    text: "Technika snowballing je v oblasti práce s informačnými zdrojmi chápaná ako vyhľadávanie referencií v zozname literatúry iných referencií alebo v zozname ich citácií. Doplň jedno slovo: vyhľadávanie ___________ .",
    accepted: ["referencii", "referencií"],
    hint: "podstatné meno (množ. číslo, genitív)",
  },
  {
    id: 58,
    type: "fillin",
    text: "Etika citovania odráža či a ako autor dodržiava etické ___________ vo vzťahu k cudzím myšlienkam a výsledkom obsiahnutým v iných dokumentoch.",
    accepted: ["normy"],
  },
  {
    id: 59,
    type: "fillin",
    text: "Ak sa zátvorka s citačným odkazom nachádza na konci vety, tak sa uvádza __________ .",
    accepted: ["pred bodkou"],
  },
  {
    id: 60,
    type: "truefalse",
    text: "Bakalárska práca je písomná odborná správa o vlastnej myšlienkovej a praktickej činnosti, ktorej obsah a zmysel zodpovedá aktuálnym požiadavkám doby a ktorej pozitívnym dôsledkom je skvalitnenie vlastného pedagogického pôsobenia.",
    answer: false,
  },
  {
    id: 61,
    type: "single",
    text: "Z hľadiska autorskej etiky je ideálne, ak:",
    options: [
      "práca obsahuje omnoho viac parafráz ako priamych citácií",
      "práca obsahuje viac priamych citácií ako parafráz",
      "práca neobsahuje žiadne citácie",
      "práca obsahuje iba citácie, žiadny vlastný text",
    ],
    answer: 0,
  },
  {
    id: 62,
    type: "fillin",
    text: "Kazuistika je ____________ štúdia.",
    accepted: ["pripadova", "prípadová"],
  },
  {
    id: 63,
    type: "single",
    text: "Ktorý z nasledujúcich výrokov je korektný?",
    options: [
      "Pri parafrázach vždy uvádzam číslo strany, no nepoužívam kurzívu.",
      "Pri priamych parafrázach vždy používam kurzívu a číslo strany uvádzam do zoznamu použitej literatúry.",
      "Priame citácie odlišujem od parafráz kurzívou a uvedením strany.",
      "Parafrázy odlišujem od priamych citácií kurzívou a uvedením strany.",
    ],
    answer: 2,
  },
  {
    id: 64,
    type: "multi",
    text: "Požiadavky na bakalársku prácu uvedené v dokumente Usmernenie k tvorbe bakalárskych prác na pedagogickej fakulte v Prešove sa riadia:",
    options: [
      "učebnými osnovami študijných programov",
      "zákonom o vysokých školách č. 131/2002 Z. z. a jeho novelami",
      "informačnými listami jednotlivých predmetov",
      "študijným poriadkom Prešovskej univerzity v Prešove",
      "obsahovým a výkonovým štandardom študijného programu",
      "smernicou o náležitostiach záverečných prác, ich bibliografickej registrácii, kontrole originality, uchovávaní a sprístupňovaní",
    ],
    answers: [1, 3, 5],
  },
  {
    id: 65,
    type: "single",
    text: "Citovať nemusíme:",
    options: CITE_NEMUSIME_OPTIONS,
    answer: 1,
  },
  {
    id: 66,
    type: "single",
    text: "Pri odkazovaní na použitý zdroj tzv. harvardským systémom, ak sa meno autora v citovanom či parafrázovanom texte neuvádza, tak v zátvorke treba uviesť:",
    options: [
      "len rok vydania publikácie",
      "meno autora a rok vydania v tvare: meno a priezvisko, medzera, čiarka a rok",
      "meno autora a rok vydania publikácie v tvare: priezvisko, medzera, rok",
    ],
    answer: 2,
  },
  {
    id: 67,
    type: "single",
    text: "Označte správnu formu citačného zápisu, ktorý nasleduje za citátom (priama citácia):",
    options: [
      "(POLÁK 1999)",
      "(Polák, 1999, s. 7)",
      "(Polák 1999)",
      "(Polák 1999, s. 7)",
    ],
    answer: 3,
  },
  {
    id: 68,
    type: "truefalse",
    text: "Podľa princípov písania akademického textu kontext (známe) je vo vete na konci, nové a dôležité na začiatku vety.",
    answer: false,
  },
  {
    id: 69,
    type: "single",
    text: "Preberanie textu (slov, myšlienok, ale aj tabuliek, obrázkov, grafov...) iných autorov a vydávanie ho za svoj vlastný bez uvedenia zdrojov sa označuje ako:",
    options: [
      "kompilát",
      "parafráza",
      "nepriama citácia",
      "plagiát",
      "priama citácia",
    ],
    answer: 3,
  },
  {
    id: 70,
    type: "single",
    text: "OBERT, V., 2006. Návraty a odkazy. Nitra: Univerzita Konštantína Filozofa. ISBN 80-8094-046-0. Túto monografiu citujeme odkazom v texte ako: (opakovanie)",
    options: OBERT_OPTIONS,
    answer: 0,
  },
  {
    id: 71,
    type: "truefalse",
    text: "Pri práci so zdrojovou literatúrou by mal študent preukázať porozumenie problematiky tým, že dokáže porovnávať teoretické koncepty a empirické zistenia z viacerých študovaných zdrojov.",
    answer: true,
  },
  {
    id: 72,
    type: "truefalse",
    text: "Za dôveryhodný internetový zdroj pri tvorbe bakalárskej práce môžeme považovať elektronické odborné časopisy, v ktorých je okrem iného uvedené zloženie redakcie, registračné číslo ISSN, poprípade zaradenie časopisu vo vedeckej databáze.",
    answer: true,
  },
  {
    id: 73,
    type: "multi",
    text: "Povinnými súčasťami bakalárskej práce sú:",
    options: [
      "predhovor",
      "abstrakt",
      "poďakovanie",
      "záver",
      "zoznam značiek a skratiek",
      "obsah",
      "prílohy",
    ],
    answers: [1, 3, 5],
  },
  {
    id: 74,
    type: "single",
    text: "Autorský vklad znamená, že:",
    options: [
      "autor ponúka vlastnú interpretáciu či závery založené na odborných faktoch",
      "autor sprostredkováva vlastné interpretácie založené na pocitoch vzťahujúcich sa k danej téme",
      "autor sprostredkováva názory iných odborníkov na tému",
      "autor ponúka vlastné názory na danú tému",
    ],
    answer: 0,
  },
  {
    id: 75,
    type: "multi",
    text: "Ktoré z nasledujúcich vyjadrení platia pre abstrakt?",
    options: [
      "je povinnou súčasťou bakalárskej práce a umiestňuje sa za titulný list na samostatnú novú stranu",
      "pri štylizácii sa používajú celé vety, slovesá v trpnom rode a v tretej osobe, využíva sa autorský plurál",
      "je vstupnou časťou práce, v ktorej je uvedené, na čo je práca zameraná, čo bolo podnetom na voľbu danej problematiky",
      "stručne a výstižne charakterizuje stav poznania v oblasti, ktorá je predmetom práce, štruktúru a opis kapitol",
      "píše sa súvisle ako jeden odsek",
      "uvádza sa povinne v slovenskom a anglickom jazyku, každá jazyková verzia na samostatnej strane",
    ],
    answers: [0, 1, 4, 5],
  },
  {
    id: 76,
    type: "single",
    text: "Ak sa zátvorka s citačným odkazom nachádza na konci vety, tak sa uvádza:",
    options: [
      "za bodkou",
      "pred bodkou",
      "môže byť pred bodkou aj za bodkou — závisí to od toho, či ide o citát alebo parafrázu",
    ],
    answer: 1,
  },
  {
    id: 77,
    type: "multi",
    text: "V odbornom texte by sa nemali používať:",
    options: [
      "emocionálne a expresívne výrazy",
      "jednočlenné oznamovacie vety",
      "cudzie slová",
      "skratky a značky",
      "súvetia",
      "zvolacie vety",
    ],
    answers: [0, 1, 5],
  },
  {
    id: 78,
    type: "single",
    text: "Ako sa tiež označuje zmena kľúčových slov a fráz v kopírovanom texte, ale zachovanie obsahu zdroja?",
    options: [
      "hybrid",
      "recyklovanie",
      "CTRL-C (žalúzie)",
      "kópia",
      "klonovanie",
      "agregátor",
      "maskovanie",
      "remix",
      "autoplagizovanie",
    ],
    answer: 6,
  },
  {
    id: 79,
    type: "single",
    text: "Pri štylizácii abstraktu sa používa: (opakovanie)",
    options: [
      "celé vety, slovesá v trpnom rode, v prvej osobe a využíva sa autorský plurál",
      "celé vety, slovesá v trpnom rode, v tretej osobe a využíva sa autorský plurál",
      "celé vety, slovesá v činnom rode, v prvej osobe a využíva sa autorský plurál",
    ],
    answer: 1,
  },
  {
    id: 80,
    type: "single",
    text: "Technika snowballing (technika snehovej gule) je v oblasti práce s informačnými zdrojmi chápaná ako: (opakovanie)",
    options: [
      "vyhľadávanie pomocou Boolean operátorov",
      "opakovaná rešerš s postupným rozširovaním zoznamu kľúčových slov",
      "vyhľadávanie referencií v zozname literatúry iných referencií alebo v zozname ich citácií",
      "vyhľadávanie v citačných databázach pomocou kľúčových slov",
    ],
    answer: 2,
  },
  {
    id: 81,
    type: "truefalse",
    text: "Práca sa píše v prvej osobe jednotného čísla.",
    answer: false,
  },
  {
    id: 82,
    type: "single",
    text: "Abstrakt bakalárskej práce sa formálne umiestňuje:",
    options: [
      "hneď za obsahom bakalárskej práce",
      "hneď za titulným listom práce",
      "hneď za čestným vyhlásením práce",
    ],
    answer: 1,
  },
  {
    id: 83,
    type: "single",
    text: "Označte správny zápis nadpisu podkapitoly:",
    options: [
      "2.3 Charakteristika ....veku",
      "2.3 Charakteristika ....veku.",
      "2.3. Charakteristika ....veku",
      "2.3. Charakteristika ....veku.",
    ],
    answer: 0,
  },
  {
    id: 84,
    type: "single",
    text: "Text práce má byť zarovnaný:",
    options: ["vľavo", "podľa okrajov do bloku", "vpravo", "na stred"],
    answer: 1,
  },
  {
    id: 85,
    type: "single",
    text: "Doslovne prevzatý text zo zdrojového dokumentu, vymedzený úvodzovkami, sa nazýva:",
    options: ["zdroj", "citát", "bibliografický odkaz", "parafráza"],
    answer: 1,
  },
  {
    id: 86,
    type: "fillin",
    text: "Knižná publikácia, ktorá pod spoločným názvom prináša súbor samostatných, vzájomne príbuzných textov, sa nazýva:",
    accepted: ["zbornik", "zborník"],
  },
  {
    id: 87,
    type: "multi",
    text: "Požiadavky na bakalársku prácu uvedené v dokumente Usmernenie k tvorbe bakalárskych prác na pedagogickej fakulte sa riadia: (opakovanie)",
    options: [
      "učebnými osnovami študijných programov",
      "smernicou o náležitostiach záverečných prác, ich bibliografickej registrácii, kontrole originality, uchovávaní a sprístupňovaní",
      "informačnými listami jednotlivých predmetov",
      "študijným poriadkom Prešovskej univerzity v Prešove",
      "obsahovým a výkonovým štandardom študijného programu",
      "zákonom o vysokých školách č. 131/2002 Z. z. a jeho novelami",
    ],
    answers: [1, 3, 5],
  },
  {
    id: 88,
    type: "matching",
    text: "Priraďte k charakteristike typ vedeckej alebo odbornej publikácie:",
    left: [
      "Vedecká publikácia určená úzkemu okruhu čitateľov, ktorá sa podrobne a vedecky precízne venuje jednej téme v rámci istej oblasti vedy a prináša nové poznatky",
      "Vedecká alebo odborná publikácia, v ktorej sa nachádzajú štúdie a odborné články viacerých autorov súvisiace zvyčajne s jednou, širšie alebo užšie vymedzenou témou",
      "Odborná publikácia určená širšiemu okruhu čitateľov, ktorá pre potreby štúdia predmetnej oblasti predkladá usporiadaný systém podstatných overených a spoľahlivých poznatkov s oporou o najnovšie zistenia",
    ],
    right: ["monografia", "zborník", "vysokoškolská učebnica"],
    pairs: [
      [0, 0],
      [1, 1],
      [2, 2],
    ],
  },
  {
    id: 89,
    type: "fillin",
    text: "Ako sa označuje využívanie zaplateného textu napísaného niekým iným, ktoré je vážnym porušením autorskej etiky?",
    accepted: ["kupa", "kúpa"],
  },
  {
    id: 90,
    type: "single",
    text: "Ktorý citačný zápis sa v univerzitnej smernici používa pre citovanie kapitoly v monografii?",
    options: [
      "MIŇOVÁ, M. Predškolská a elementárna didaktika. 2013.",
      "MIŇOVÁ, M., (2013) Vyučovací proces. Bibliografia: Prešov.",
      "MIŇOVÁ, M., 2013. Vyučovací proces a jeho aktéri. In: M. Portik a kol. Predškolská a elementárna didaktika. Prešov: Prešovská univerzita v Prešove. s. 34 – 47. ISBN 978-80-555-0467-4.",
    ],
    answer: 2,
  },
  {
    id: 91,
    type: "single",
    text: "Označenie tabuľky v bakalárskej práci (napr. „Tab. 1 Názov\") sa umiestňuje:",
    options: [
      "pod tabuľku",
      "nad tabuľku",
      "v samostatnom rámčeku vedľa tabuľky",
      "iba do zoznamu tabuliek na konci práce",
    ],
    answer: 1,
  },
  {
    id: 92,
    type: "fillin",
    text: "Ako sa označuje kopírovanie cudzích textov, ktoré sú síce odcitované, ale bez vlastného textu?",
    accepted: ["agregator", "agregátor"],
  },
  {
    id: 93,
    type: "single",
    text: "Prečítajte si úryvok z publikácie I. Tureka Didaktika (2008, s. 146–147): „Pojmom sebareflexia rozumieme proces premýšľania človeka o sebe samom, o svojom konaní a jeho výsledkoch.\" Ktorý z nasledujúcich výrokov z úryvku NEvyplýva?",
    options: [
      "Sebareflexia je premýšľanie jednotlivca o sebe samom.",
      "Sebareflexia zahŕňa premýšľanie o vlastnom konaní.",
      "Sebareflexia je vrodená vlastnosť, ktorá sa nedá rozvíjať.",
      "Sebareflexia sa týka aj výsledkov vlastného konania.",
    ],
    answer: 2,
    note: "⚠️ Originálny úryvok nie je v podkladoch — odpoveď je rekonštruovaná podľa logiky výrokov.",
  },
  {
    id: 94,
    type: "fillin",
    text: "Vypracovanie bibliografického zoznamu relevantných dokumentov v určitej téme, ktorý obsahuje základné bibliografické údaje (autor, názov, miesto a rok vydania, počet strán) a prípadne ďalší popis (predmetové heslá, abstrakt a pod.) sa nazýva:",
    accepted: ["reserš", "rešerš", "reserš"],
  },
  {
    id: 95,
    type: "multi",
    text: "Vyberte jednu alebo viac možností, ktoré charakterizujú záver bakalárskej práce:",
    options: [
      "má súvisieť s jadrom práce, jeho účelom je zhrnúť výsledky a stručne vyjadriť význam práce",
      "podobne ako úvod, záver prácu dokončuje — preto je potrebné zhodnotiť prácu ako celok",
      "obsahuje vecné závery, sumarizáciu práce, vlastný prínos autora, pohľad autora na stanovené ciele",
      "musí nadväzovať na výklad, informácie, komparáciu zdrojov, teoretické úvahy a argumenty v jadre práce",
      "nie je prepisom úvodu, opakovaním niektorých častí práce a ďalším teoretizovaním",
      "odporúčaný rozsah záveru bakalárskej práce je cca 1 – 2 strany",
      "obsahuje predovšetkým nové, doteraz nepublikované teoretické úvahy a hypotézy",
    ],
    answers: [0, 1, 2, 3, 4, 5],
  },
  {
    id: 96,
    type: "truefalse",
    text: "Práca sa píše v prvej osobe jednotného čísla a v trpnom rode.",
    answer: false,
  },
  {
    id: 97,
    type: "single",
    text: "Označte správnu formu citačného zápisu, ktorý nasleduje za citátom (priamou citáciou): (opakovanie)",
    options: [
      "(POLÁK 1999)",
      "(Polák, 1999, s. 7)",
      "(Polák 1999)",
      "(Polák 1999, s. 7)",
    ],
    answer: 3,
  },
  {
    id: 98,
    type: "single",
    text: "Prečítajte si úryvok z publikácie Z. Kollárikovej, B. Pupalu a kol. „Predškolská a elementárna pedagogika\" — ktoré z nasledujúcich tvrdení z úryvku vyplýva?",
    options: [
      "Predškolská pedagogika sa zameriava na vzdelávanie a výchovu detí v predškolskom veku.",
      "Predškolská pedagogika sa zaoberá výlučne motorickým vývinom dieťaťa.",
      "Predškolská pedagogika nesúvisí s elementárnou pedagogikou.",
    ],
    answer: 0,
    note: "⚠️ Pôvodný úryvok nebol súčasťou podkladov — odpoveď a možnosti sú rekonštruované, treba overiť so zdrojom.",
  },
  {
    id: 99,
    type: "matching",
    text: "Podľa názvu autora určte, pre ktorú tematickú oblasť poskytne táto publikácia autorovi bakalárskej práce najviac relevantných zdrojových informácií:",
    left: ["Hendl", "Langmeier", "Kalhous"],
    right: [
      "metodológia výskumu / kvalitatívne metódy",
      "vývinová psychológia",
      "školská didaktika a pedagogika",
    ],
    pairs: [
      [0, 0],
      [1, 1],
      [2, 2],
    ],
    note: "⚠️ Konkrétne tituly nie sú uvedené v podkladoch — priradenie podľa najznámejších publikácií autorov.",
  },
  {
    id: 100,
    type: "single",
    text: "Abstrakt obsahuje:",
    options: [
      "informáciu o cieľoch práce, jej stručnom obsahu a v závere abstraktu sa charakterizuje splnenie cieľa, použité metódy, výsledky a závery celej práce",
      "iba zoznam použitej literatúry",
      "iba kľúčové slová",
      "iba osobné údaje autora a vedúceho práce",
    ],
    answer: 0,
  },
];
