import type { Question } from "../types";

/**
 * Otázky pre predmet „Patopsychológia" (Dubayová, PdF Prešov).
 * Zdroj: skenované testové papiere s ručne vyznačenými správnymi odpoveďami
 * (zvýraznené ružovou/zelenou farbou).
 *
 * Mix viacerých variantov testu — niektoré otázky majú podobný koncept
 * (napr. Q9/Q19 „Nevhodné výchovné pôsobenie") ale rôzne sformulované možnosti.
 * Pre dedup v skúškovom režime sú zaznamenané v lib/duplicates.ts.
 */

export const questions: Question[] = [
  {
    id: 1,
    type: "multi",
    text: "Pre deti s ťažkou mentálnou retardáciou je charakteristické, že:",
    options: [
      "neadekvátne reagujú na podnety, napr. zima, chlad, teplo",
      "deti sú motoricky zručné, postihnutý je u nich len intelekt",
      "sa dokážu o seba postarať, nutný je však dozor inej osoby",
      "sa dokážu naučiť s porozumením používať niekoľko slov",
    ],
    answers: [0, 3],
  },
  {
    id: 2,
    type: "multi",
    text: "Antisociálna porucha správania sa môže u dieťaťa prejavovať aj ako:",
    options: [
      "agresívne a ubližujúce správanie voči spolužiakom",
      "správanie, ktoré sa vyskytuje častejšie u dievčat ako u chlapcov",
      "sebapoškodzovanie a užívanie návykových látok",
      "správanie dieťaťa, ktoré porušuje práva a slobody ostatných ľudí",
    ],
    answers: [0, 3],
  },
  {
    id: 3,
    type: "multi",
    text: "Ku znakom rodiny mladistvého delikventa patrí napríklad aj:",
    options: [
      "vysoká konfliktnosť medzi členmi rodiny",
      "stabilita a otvorená komunikácia v rodine",
      "nejednotnosť výchovného pôsobenia rodičov",
      "demokratický štýl rozhodovania",
    ],
    answers: [0, 2],
  },
  {
    id: 4,
    type: "single",
    text: "Pri ukladaní do pamäte detí s mentálnym postihnutím musíme myslieť na to, že:",
    options: [
      "majú spomalené tempo tvorenia pamäťových spojení",
      "pri úmyselnom zapamätávaní je ich výkon iba o máličko vyšší ako pri neúmyselnom",
      "ich pamäťový výkon je rovnaký ako u bežnej populácie",
    ],
    answer: 0,
  },
  {
    id: 5,
    type: "multi",
    text: "Ku kritériám, ktoré vystihujú normálne sa správajúceho jedinca patrí (podľa Syřišťovej):",
    options: [
      "pocit autonómie, schopnosť sebakontroly a schopnosť samostatného rozhodovania",
      "odolnosť voči stresu a úzkosti",
      "schopnosť prispôsobiť sa životu v spoločnosti (tzn. schopnosť sociálnej adaptácie)",
      "vyhýbanie sa zodpovednosti",
    ],
    answers: [0, 2],
  },
  {
    id: 6,
    type: "multi",
    text: "Psychosociálne narušenie znamená, že:",
    options: [
      "dochádza k zmenám vo vývine a stave psychiky pod vplyvom spoločnosti, v ktorej jedinec vyrastá alebo sa pohybuje",
      "prejavuje sa v emocionálnej, mravnej, sociálnej alebo vo výchovnej oblasti",
      "ide o výlučne biologicky podmienené narušenie",
      "ide o krátkodobý jav, ktorý spontánne ustúpi",
    ],
    answers: [0, 1],
  },
  {
    id: 7,
    type: "multi",
    text: "Bezpečná vzťahová väzba:",
    options: [
      "sa najintenzívnejšie tvorí v prvom roku života",
      "sa vytvára až po vstupe dieťaťa do školy",
      "sa vytvára u detí, ktorých potreby boli dostatočne uspokojované",
      "závisí výlučne od ekonomického zázemia rodiny",
    ],
    answers: [0, 2],
  },
  {
    id: 8,
    type: "multi",
    text: "Syřišťová tvrdí, že ku kritériám normálnosti patrí:",
    options: [
      "schopnosť konať autonómne a nezávisle",
      "potreba neustáleho dozoru",
      "úplná podriadenosť autorite",
      "sociálna adaptácia",
    ],
    answers: [0, 3],
  },
  {
    id: 9,
    type: "multi",
    text: "Nevhodné výchovné pôsobenie v rodine sa u dieťaťa môže prejaviť napríklad ako:",
    options: [
      "rozvinuté pracovné návyky",
      "zlé pracovné návyky",
      "neprimerané emocionálne prejavy, impulzívnosť, netaktné a nevhodné správanie",
      "vyrovnané a stabilné správanie",
    ],
    answers: [1, 2],
  },
  {
    id: 10,
    type: "single",
    text: "K príčinám zníženého školského výkonu dieťaťa s mentálnym postihnutím patrí aj:",
    options: [
      "porucha vytvárania pamäťovej stopy",
      "nadmerná motivácia k učeniu",
      "vysoká schopnosť abstrakcie",
    ],
    answer: 0,
  },
  {
    id: 11,
    type: "truefalse",
    text: "Pre myslenie osôb s mentálnym postihnutím je charakteristické, že problémy riešia často pomocou metódy pokus-omyl.",
    answer: true,
  },
  {
    id: 12,
    type: "multi",
    text: "Deti s mentálnym postihnutím majú v oblasti pamäte problém s:",
    options: [
      "ukladaním informácií do dlhodobej pamäte",
      "triedením a ukladaním informácií na základe logických súvislostí",
      "rýchlym automatickým zapamätaním informácií",
      "vybavovaním nadmerne emocionálnych spomienok",
    ],
    answers: [0, 1],
  },
  {
    id: 13,
    type: "multi",
    text: "Deti s mentálnym postihnutím majú v oblasti pozornosti problém s:",
    options: [
      "nesprávnym postupom pri zameriavaní pozornosti",
      "prenášaním pozornosti",
      "udržaním pasívnej pozornosti na známom podnete",
      "delením pozornosti",
    ],
    answers: [0, 1, 3],
  },
  {
    id: 14,
    type: "multi",
    text: "Porucha správania je spojená s:",
    options: [
      "krátkodobou (do 2 týždňov) reakciou na záťažovú situáciu",
      "neschopnosťou nadväzovať a udržiavať zdravé priateľské vzťahy",
      "pretrvávaním problémového správania viac ako 6 mesiacov",
      "izolovaným jednorazovým incidentom",
    ],
    answers: [1, 2],
  },
  {
    id: 15,
    type: "fillin",
    text: "Závažné postihnutie vývinu rozumových schopností, ktoré vedie aj k významnému obmedzeniu v oblasti adaptácie v sociálnom prostredí, sa nazýva:",
    accepted: ["mentálna retardácia", "mentalna retardacia"],
  },
  {
    id: 16,
    type: "truefalse",
    text: "Inteligencia znamená schopnosť rozumieť faktom, vzťahom a významom.",
    answer: true,
  },
  {
    id: 17,
    type: "single",
    text: "Ktoré z nasledujúcich NIE JE klasifikované ako biologický faktor psychosociálneho narušenia?",
    options: [
      "Genetické dispozície",
      "Emocionálna deprivácia",
      "Pôrodné poškodenie centrálneho nervového systému",
      "Vrodené metabolické poruchy",
    ],
    answer: 1,
  },
  {
    id: 18,
    type: "multi",
    text: "Porucha správania je:",
    options: [
      "krátkodobou reakciou na bežný školský stres",
      "charakteristická nerešpektovaním spoločenských noriem",
      "inak nazývaná aj poruchou v oblasti socializácie",
      "charakteristická disociálnym, agresívnym a vzdorovitým správaním sa",
    ],
    answers: [1, 2, 3],
  },
  {
    id: 19,
    type: "truefalse",
    text: "Následky deprivácie na vývin dieťaťa sú tým horšie, čím v mladšom veku sa dieťa stretlo s deprivačnou skúsenosťou.",
    answer: true,
  },
  {
    id: 20,
    type: "truefalse",
    text: "Deprivácia základných biologických potrieb sa podpisuje na telesnom vývine dieťaťa a dlhodobé strádanie môže viesť až k zániku organizmu.",
    answer: true,
  },
  {
    id: 21,
    type: "multi",
    text: "K symptómom porúch správania patrí:",
    options: [
      "napr.: neposlúchnutie učiteľa, aby sa dieťa vyzulo",
      "záškoláctvo",
      "vzdorovité správanie",
      "ranné bolenie brucha pred odchodom do školy",
    ],
    answers: [0, 1, 2],
  },
  {
    id: 22,
    type: "multi",
    text: "Pri neistej vzťahovej väzbe rozpoznávame tieto 3 typy:",
    options: [
      "Neistá dezorganizovaná",
      "Neistá nesocializovaná",
      "Neistá ambivalentná",
      "Neistá vyhýbavá",
    ],
    answers: [0, 2, 3],
    exactCount: 3,
  },
  {
    id: 23,
    type: "fillin",
    text: "Výchovný štýl charakteristický nejednotnými výchovnými postupmi rodičov a neustále sa meniacimi pravidlami sa nazýva:",
    accepted: ["ambivalentný", "ambivalentny"],
  },
  {
    id: 24,
    type: "multi",
    text: "Klamstvo je (3 správne):",
    options: [
      "Prikrášľovanie si reality u detí v predškolskom veku",
      "Úmyselné zatajovanie skutočnosti",
      "Správanie, ktoré nie je vhodné trestať u detí v predškolskom veku",
      "Deťmi používané na to, aby sa vyhli trestu",
    ],
    answers: [0, 1, 3],
    exactCount: 3,
    note: "⚠️ Možnosť „c\" (nie je vhodné trestať) je v poznámkach trochu nejasná — zaradil som a/b/d ako 3 typické charakteristiky klamstva. Overiť so smernicou.",
  },
  {
    id: 25,
    type: "multi",
    text: "Porucha správania je (1 alebo viac, 2 správne):",
    options: [
      "Inak nazývaná aj poruchou v oblasti pozornosti",
      "Charakteristická disociálnym, agresívnym a vzdorovitým správaním sa",
      "Charakteristická anomálnym, animálnym a agresívnym správaním sa",
      "Inak nazývaná aj poruchou v oblasti socializácie",
    ],
    answers: [1, 3],
    exactCount: 2,
  },
  {
    id: 26,
    type: "multi",
    text: "Patopsychológia:",
    options: [
      "Skúma aj špecifiká vývinu dieťaťa v určitom zmyslovom alebo inom nedostatku",
      "Je podpornou vednou disciplínou špec. pedagogiky",
      "Je hybridnou vednou disciplínou",
      "Sa zaoberá teóriou a praxou výchovy a edukácie detí, mládeže a dospelých vyžadujúcich špeciálnu starostlivosť",
    ],
    answers: [0, 1],
    note: "⚠️ Možnosť „d\" je definícia špeciálnej pedagogiky — nie patopsychológie.",
  },
  {
    id: 27,
    type: "fillin",
    text: "Jav, kedy dochádza k neuspokojovaniu potrieb dieťaťa v dostatočnej miere a dostatočne dlhý čas, sa nazýva:",
    accepted: ["deprivácia", "deprivacia"],
  },
  {
    id: 28,
    type: "truefalse",
    text: "Deti s mentálnym postihnutím majú v oblasti pozornosti problém s triedením a ukladaním informácií na základe logických súvislostí.",
    answer: true,
  },
  {
    id: 29,
    type: "multi",
    text: "Pod nepriaznivým životným nedostatkom sa môže predstaviť napríklad:",
    options: [
      "senzorické alebo somatické postihnutie",
      "život v málo podnetnom prostredí",
      "deprivácia",
      "život bez informačných technológií",
    ],
    answers: [0, 1, 2],
  },
  {
    id: 30,
    type: "multi",
    text: "Správanie otca, ktoré má negatívny vplyv na emocionálny vývin dieťaťa, je napríklad (1 alebo viac):",
    options: [
      "zameranosť na svoje koníčky",
      "rešpektovanie nálad partnerky",
      "závislosť na alkohole",
      "neschopnosť poskytnúť dieťaťu uspokojenie ani základných potrieb",
    ],
    answers: [0, 2, 3],
  },
  {
    id: 31,
    type: "truefalse",
    text: "Správne súčasné označenie jedinca s postihnutím je „jedinec vyžadujúci osobitnú starostlivosť\".",
    answer: false,
  },
  {
    id: 32,
    type: "truefalse",
    text: "Následky emocionálnej traumy a deprivácie spôsobenej nesprávnym zaobchádzaním zo strany rodičov závisia aj od osoby, ktorá sa k dieťaťu nevhodne správa.",
    answer: true,
  },
  {
    id: 33,
    type: "multi",
    text: "Negatívny vplyv na emocionálny vývin dieťaťa má matka, ktorá (1 alebo viac):",
    options: [
      "má nízky ekonomický príjem",
      "striedavo prejavuje lásku dieťaťu alebo ho odmieta, čo však nezávisí na ničom, čo dieťa urobí",
      "má už druhého životného partnera",
      "vyžaduje poslušnosť a podriadenosť a poskytuje málo pozitívnej spätnej väzby",
    ],
    answers: [1, 3],
  },
  {
    id: 34,
    type: "multi",
    text: "Dysfunkčná rodina je charakteristická:",
    options: [
      "asociálnymi rodičmi",
      "aktívnymi rodičmi",
      "otvorenou a aktívnou komunikáciou",
      "nejasným rozdelením zodpovednosti a úloh",
    ],
    answers: [0, 3],
  },
  {
    id: 35,
    type: "multi",
    text: "Porucha správania sa môže prejavovať u detí aj ako (1 alebo viac):",
    options: [
      "nadmerné bitkárstvo a krutosť voči iným ľuďom a zvieratám",
      "správanie únikového charakteru",
      "krádeže, opakované klamstvo, záškoláctvo a úteky z domu",
      "pubertálna rebélia",
    ],
    answers: [0, 2],
  },
  {
    id: 36,
    type: "multi",
    text: "Deprivácia znamená:",
    options: [
      "napr. aj dlhodobé vystavenie dieťaťa nedostatku lásky a pozornosti",
      "dlhodobo nedostatočné uspokojovanie základných potrieb dieťaťa",
      "stav, ktorý sa nevyskytuje v rodinách s dobrým ekonomickým zázemím",
      "rýchle uspokojovanie základných potrieb dieťaťa",
    ],
    answers: [0, 1],
  },
];
